version: sqlite3
# Database Schema and Table Schema
database:
  name: LendingClubDB
  general:
    username: LCusers
    use: store data from Lending Club
  schemas:
    lc_main_20:
      tablename: accepted_main_20
      fields:
        id: INTEGER
        funded_amnt_inv: REAL
        term: REAL
        int_rate: REAL
        emp_length: REAL
        out_prncp_inv: REAL
        total_pymnt_inv: REAL
        last_pymnt_amnt: REAL
        mths_since_recent_inq: REAL
        percent_bc_gt_75: REAL
        mean_fico: REAL
        sub_grade: TEXT
        home_ownership: TEXT
        loan_status: TEXT
        purpose: TEXT
        addr_state: TEXT
        issue_d: TIMESTAMP
        earliest_cr_line: TIMESTAMP
        last_pymnt_d: TIMESTAMP
        last_credit_pull_d: TIMESTAMP
      primaryKey: id
    lc_sec_20:
      tablename: accepted_secondary
      fields:
        id: INTEGER
        member_id: REAL
        loan_amnt: REAL
        funded_amnt: REAL
        installment: REAL
        grade: TEXT
        emp_title: TEXT
        annual_inc: REAL
        verification_status: TEXT
        pymnt_plan: TEXT
        url: TEXT
        desc: TEXT
        title: TEXT
        zip_code: TEXT
        dti: REAL
        delinq_2yrs: REAL
        fico_range_low: REAL
        fico_range_high: REAL
        inq_last_6mths: REAL
        mths_since_last_delinq: REAL
        mths_since_last_record: REAL
        open_acc: REAL
        pub_rec: REAL
        revol_bal: REAL
        revol_util: REAL
        total_acc: REAL
        initial_list_status: TEXT
        out_prncp: REAL
        total_pymnt: REAL
        total_rec_prncp: REAL
        total_rec_int: REAL
        total_rec_late_fee: REAL
        recoveries: REAL
        collection_recovery_fee: REAL
        next_pymnt_d: TEXT
        last_fico_range_high: REAL
        last_fico_range_low: REAL
        collections_12_mths_ex_med: REAL
        mths_since_last_major_derog: REAL
        policy_code: REAL
        application_type: TEXT
        annual_inc_joint: REAL
        dti_joint: REAL
        verification_status_joint: TEXT
        acc_now_delinq: REAL
        tot_coll_amt: REAL
        tot_cur_bal: REAL
        open_acc_6m: REAL
        open_act_il: REAL
        open_il_12m: REAL
        open_il_24m: REAL
        mths_since_rcnt_il: REAL
        total_bal_il: REAL
        il_util: REAL
        open_rv_12m: REAL
        open_rv_24m: REAL
        max_bal_bc: REAL
        all_util: REAL
        total_rev_hi_lim: REAL
        inq_fi: REAL
        total_cu_tl: REAL
        inq_last_12m: REAL
        acc_open_past_24mths: REAL
        avg_cur_bal: REAL
        bc_open_to_buy: REAL
        bc_util: REAL
        chargeoff_within_12_mths: REAL
        delinq_amnt: REAL
        mo_sin_old_il_acct: REAL
        mo_sin_old_rev_tl_op: REAL
        mo_sin_rcnt_rev_tl_op: REAL
        mo_sin_rcnt_tl: REAL
        mort_acc: REAL
        mths_since_recent_bc: REAL
        mths_since_recent_bc_dlq: REAL
        mths_since_recent_revol_delinq: REAL
        num_accts_ever_120_pd: REAL
        num_actv_bc_tl: REAL
        num_actv_rev_tl: REAL
        num_bc_sats: REAL
        num_bc_tl: REAL
        num_il_tl: REAL
        num_op_rev_tl: REAL
        num_rev_accts: REAL
        num_rev_tl_bal_gt_0: REAL
        num_sats: REAL
        num_tl_120dpd_2m: REAL
        num_tl_30dpd: REAL
        num_tl_90g_dpd_24m: REAL
        num_tl_op_past_12m: REAL
        pct_tl_nvr_dlq: REAL
        pub_rec_bankruptcies: REAL
        tax_liens: REAL
        tot_hi_cred_lim: REAL
        total_bal_ex_mort: REAL
        total_bc_limit: REAL
        total_il_high_credit_limit: REAL
        revol_bal_joint: REAL
        sec_app_fico_range_low: REAL
        sec_app_fico_range_high: REAL
        sec_app_earliest_cr_line: TEXT
        sec_app_inq_last_6mths: REAL
        sec_app_mort_acc: REAL
        sec_app_open_acc: REAL
        sec_app_revol_util: REAL
        sec_app_open_act_il: REAL
        sec_app_num_rev_accts: REAL
        sec_app_chargeoff_within_12_mths: REAL
        sec_app_collections_12_mths_ex_med: REAL
        sec_app_mths_since_last_major_derog: REAL
        hardship_flag: TEXT
        hardship_type: TEXT
        hardship_reason: TEXT
        hardship_status: TEXT
        deferral_term: REAL
        hardship_amount: REAL
        hardship_start_date: TEXT
        hardship_end_date: TEXT
        payment_plan_start_date: TEXT
        hardship_length: REAL
        hardship_dpd: REAL
        hardship_loan_status: TEXT
        orig_projected_additional_accrued_interest: REAL
        hardship_payoff_balance_amount: REAL
        hardship_last_payment_amount: REAL
        disbursement_method: TEXT
        debt_settlement_flag: TEXT
        debt_settlement_flag_date: TEXT
        settlement_status: TEXT
        settlement_date: TEXT
        settlement_amount: REAL
        settlement_percentage: REAL
        settlement_term: REAL
      primaryKey: id

# Specifics for data pull process
datapull:
  source:
    kaggle:
      username: pkromkowski
      key: 72cd8d43b75365711072de7455789c8a
      apipath: wordsforthewise/lending-club
    local:
      apipath: ./Data/source/
  general:
    rawname: accepted
    sourcepath: ./Data/source/
    rawpath: ./Data/raw/
    save_raw: 0

# Specifics for data trancsformation process
datatransform:
  cleanname: accepted
  cleanpath: ./Data/clean/

# Specifics for data loading to database process
dataload:
  databasepath: ./Data/database/
  finalname: accepted
  logic: append
